### ISSUE TITLE
Make PayPal on Shop Settings Optional

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#144]
Currently, we have PayPal as mandatory, or none at all.  This is not optimal.

Administrators can disable PayPal on the Shop Settings page with a Shortcode:

http://www.wcvendors.com/knowledgebase/turn-paypal/

.....however then it disables PayPal for EVERYONE.

With PayPal enabled, ALL vendors have to input a PayPal email otherwise they cant even update their store name or descriptions.  So if they dont have PayPal, they'll enter a fake email, which is no good either.

1.) Make the PayPal email address "not required" on Shop Settings (This is part of the class, not part of the dashboard templates)

2.) If the vendor has PayPal setup, it pays them and marks commission as paid.

3.) If vendor does not have a PayPal address on their shop settings, we do not pay that vendor, and commission gets marked as "due" and then it is the admins responsibility to pay that vendor as they see fit to do so.

**Comment by MattyLB** [comment]
This should be a required step for store setup because it defeats the
purpose that PayPal specifically outlined to me that EACH vendor should be
paid individually and directly via the chained payments method to make an
individual vendor liable for their portion of a sale, otherwise the site
owner is responsible for the full charge back amount of a customer disputes
only part of the order. This came directly from a lead business account rep
at PayPal and is the main reason I'm holding off on using this solution
until chained payments is implemented.  Don't kill the messenger, I'm just
stating what my account rep strongly warned me against.

**Comment by digitalchild** [comment]
Actually parallel payments the vendor is liable for the refunds. In a chained payment scenario the marketplace is liable. In chained payments you as the market place is the primary receiver but with parallel the money is sent directly to each vendor.
