### ISSUE TITLE
Allow usage of other Paypal plugins to pay vendors

### ISSUE THREAD

**Issue by jetlej** [wcvendors/wcvendors#175]
I use Paypal Express on my site for various reasons. If I activate the Paypal plugin that comes with WC-Vendors, my customers will see two Paypal checkout options. 

I see two ways to fix this:

1) Give an option to disable the WC Vendor Paypal plugin from being shown to front-end customers

2) Allow other Paypal plugins to be used to pay vendors

**Comment by bentasm1** [comment]
Neat idea.  Allow PayPal to pay vendors, but disallow it from the checkout page.  Makes sense to me.

**Comment by MattyLB** [comment]
Regarding PayPal Express, it does have its benefits with direct checkout options at the product, archive, cart widget and checkout levels - but would it work for accepting one payment split among multiple vendors?

While PayPal doesn't "require" vendor payments to be split, they strongly suggest this so that each vendor is responsible for their own portion of the customer's total purchase - whereas in a single payment (Express checkout scenario) one complaint for an item not received would force the store owner to be responsible for the ENTIRE purchase amount, including the amount paid for other items that were fulfilled for that purchase.

Hopefully there is a split-payment solution for PayPal Express because it is a very handy impulse purchase tool, but if there isn't I would avoid throwing this suggestion or option out to prevent liability issues and fraud from any customer that "knows" they can dispute one item for any relevent (PayPal) issue and receive a FULL refund - even though 99% of the order was fulfilled.

Hopefully I'm overthinking this but I always err on the safe side.

**Comment by bentasm1** [comment]
PayPal Express ( https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECParallelPaymens/ ) does have parallel payment support, but then at checkout you see:

Vendor Name - $90
Store Owner - $10
Total: $100

So yes, it could be written technically, but nobody would like how the checkout is displayed because it gives away their sites commission structure and looks really really weird.

**Comment by MattyLB** [comment]
Oh wow - that's good to know and interesting why they did it this way. Hmm... something to think about, I guess. Thanks for posting that!

**Comment by bentasm1** [comment]
After consideration, since you can write a one line filter for the checkout page to disable paypalap, no real need to go nuts by adding this to core and confusing people.  Special use cases can use the filter.
