### ISSUE TITLE
Expose <ul> in templates

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#243]
Lost of themes have their own tabs available: http://demo.oxygentheme.com/demo-content/shortcodes/tabs/

Line 500 of `class-wcvendors-pro-dashboard` echo's the `<ul>` for the pro dashboard. This means you'd have to wc-vendors-pro just to get at the class. Exposing the `<ul>` in the template makes more sense. You could pass `$pages` and have the loop in the template.

**Comment by digitalchild** [comment]
I'll add a filter so you can add classes but I removed the UL from the template because too many people were breaking the layout when editing things. There are literally hundreds of themes that I need to support which is why the entire dashboard is on a single page loading the framework on this page only. This ensures consistency for our pro dashboard. The templates and every single form field is available so you can customise this template as you see fit without using the tabs or drop downs that we use in the 'kitchen sink' form.

**Comment by archonic** [comment]
A filter is fine, and a better solution. Thanks!

**Comment by digitalchild** [comment]
Filter has been added and will be in next release.
