### ISSUE TITLE
How to safely add shipping cost to a commission?

### ISSUE THREAD

**Issue by CasperBraske** [wcvendors/wcvendors#318]
Hello. I'm authoring a plugin to add support to a certain shipping method.
I'm having trouble figuring out how I'm going to use your API so the shipping costs are calculated in a per package basis (instead of per product).
I thought that registering the shipping in the "pv_commissions" would be enough and your API would do the job incrementing or decrementing from the totals based on the "give_shipping" option.
Despite adding to the table right away, I want to be as less intrusive as I can. Maybe sticking with some method/function or hook I may have missed.
Your code is pretty straight forward but it has become very difficult to follow the "add due" flow.

**Comment by digitalchild** [comment]
Unfortunately at this stage everything still has to be calculated at a per product rate. It is how commissions are calculated, not per vendor or order. I am currently rethinking how commissions, payment gateways and shipping calculations work for version 2. I don't have an ETA on that but I have started work on this design, no code yet. Most of this original code was inherited from the Product Vendors plugin from years ago and hasn't really been updated. My aim is to have a clean API for version 2 to make things like this much easier to integrate and manage.

**Comment by CasperBraske** [comment]
Thank you @digitalchild for your response.
I'm already doing this [in some way] in a per-product level by inserting the shipping amount like so:

```sql
UPDATE wp_pv_commission
SET total_shipping = %d
WHERE order_id = %d
AND vendor_id = %d
LIMIT 1
```
The end result being:

|order_id|vendor_id|product_id|total_shipping|
|---|---|---|---|
|1|1|1|20|
|1|1|2|`NULL`|
|1|2|3|30|
|1|2|4|`NULL`|
|1|2|5|`NULL`|
|...|...|...|...|
|2|2|4|50|
|2|2|3|`NULL`|
|2|2|5|`NULL`|


It will insert the shipping amount into the first line it encounters the `order_id`/`vendor_id` assertion by the time of the `woocommerce_order_status_completed/processing` hook call and, since every line in that table is a "product", it is actually doing a per-product insertion. Although, regardless of what the "give_shipping" value is, it always get added to the actual commission in the reports (front- and back-end).
I'd like to display the shipping and commission values separately, as it doesn't seem semantically right to display them as one value.
Something like this would be displayed to the site owner (the first column is just a placeholder to show the give_shipping value here):

|give shipping|commission|shipping|due*|
|:---:|---|---|---|
|`true`|100|20|80 or 100|
|`false`|100|30|130|

\* what you as the owner should pay to the vendor

Another problem is that I want to make my plugin as future proof and modular as possible so that when it is deactivated, the values shown will still be the same.

I'll look into "debugging" the hooks (like `wcvendors_shipping_due` and `wcv_commissions_inserted`) and other methods to see how I can manipulate the values displayed by now.

-----------
My plugin uses packages since the shipping method itself uses this approach and I believe that many others do as well.
See, sending two products in, say, one box is pretty much cheapier than sending them separatelly depending on the product in question.
I'll try to see if something cool can be done using the current codebase and send you a PR.

**Comment by digitalchild** [comment]
I agree that there needs to be some work done with how commissions are displayed and would be more than happy to change how the commission table is displayed. I think we should be splitting them and not totalling them as it becomes hard to know what the split is without seeing the breakdown.

I'm not sure if you've dug much into the code but a few minor releases ago I quietly introduced suborders into the free code base. More work needs to be done with this so that any updates to the parent order get reflected in the child orders. The reason for this is then we can perform shipping, commissions and other things at an order level instead of at product level. This should make a LOT of things easier for integrations and also reduce a lot of possible issues we're having with code doubling up and just being in the wrong class files. I think the main commission class is a lot more complicated than it needs to be and I would like to simplify this and attach the commission to the new suborders so we can just do $new_suborder->get_commission(); 

This will also require re-thinking how commissions are calculated and handled. There is much work to be done to modernize the code base and make the API a lot more pluggable. I don't believe it was originally designed like this and I've just been forcing it to our will.

**Comment by digitalchild** [comment]
We now split out shipping and taxes in the commission table which makes it a little easier to see what the commission is made up of. Unless you require anything else I'll be closing this.

**Comment by avishai** [comment]
Say I have an order, which I've already split up into multiple shipping packages using the [Packages Configuration for WooCommerce](https://wordpress.org/plugins/packages-configuration-for-woocommerce/) plugin. In my custom shipping method, I calculate a shipping price per vendor. Where do you think would be the best way to pass that amount into the commission table for that `product_id`, `order_id`, `vendor_id` row?

**Comment by digitalchild** [comment]
If you're using pro, we already split shipping this way and do this per vendor. The latest version of pro already includes support for shipping package per order commissions now. Check out how I did this for the new shipping module in 1.4 if you have it.
