### ISSUE TITLE
Order status should be changed to 'completed' once all vendors have shipped

### ISSUE THREAD

**Issue by avishai** [wcvendors/wcvendors#375]
Once all vendors who make up an order have marked their packages as shipped, WC Vendors should automatically change the WC order status to 'completed'. Currently, an order never gets marked as completed unless an admin manually changes it.

**Comment by bentasm1** [comment]
This will never happen.  The reason?  Not all sites require orders to be "Completed".  Some leave them as processing, custom statuses, etc.

What you can do, instead, is write a filter, so that when a vendor marks an order as shipped, you can check that order and iterate through all the items in it and see if all are marked shipped, then change the status.  That's all custom code all you!

Cheers
