### ISSUE TITLE
Vendor sees reports for entire site on back end

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#4]
http://www.wcvendors.com/help/topic/vendor-reports-back-end/

Vendors are created and when they login to the back-end – they see Orders for the entire site.

**Comment by oldnava** [comment]
Hello, any news on this bug?

**Comment by bentasm1** [comment]
Not yet, no.......  Soon! :)

**Comment by spinalwiz** [comment]
Hi, I used a role manager to allow vendors to view orders in the backend and they can see orders from all other vendors as well. Presume this is related to this issue as well.

**Comment by digitalchild** [comment]
@spinalwiz you should never let your vendors see orders on the backend. Orders in woocommerce are for admins or store managers only. We do not split orders per vendor so there is no way to provide the functionality you are looking for. 

The reports bug is because Woocommerce completely re-wrote their reporting engine and none of the filters we used are available anymore.

**Comment by digitalchild** [comment]
Feature has been depreciated and will be removed in future versions.
