### ISSUE TITLE
Vendor labels can't be translated

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#451]
The translations for the vendor labels are not being translated

**Comment by mahlamusa** [comment]
The vendor labels entered in the text boxes cannot be translated because they do not exist in the translation files, they are variables and variables cannot be translated because the translator only takes a list of already existing strings and match them with the translated strings, it does not process variables before doing the translation.

One solution will be to add the strings manually to the .pot file.

Any suggestions on a way forward here?

**Comment by digitalchild** [comment]
The default values cannot be translated. So when a translation is created these values are staying as "vendor/vendors".
