### ISSUE TITLE
Loopback request failure

### ISSUE THREAD

**Issue by dvrcthewrld** [wcvendors/wcvendors#453]
On a clean install of WP with only WooCommerce and WC Vendors, Health Check reports a loopback request failure.  Disabling WCV resolves the issue.

**Comment by dvrcthewrld** [comment]
This is from the Health Check plugin.  Request is successful upon deactivating WCV.
![Image of failure](https://i.imgur.com/kTPBiTU.png)

**Comment by mahlamusa** [comment]
Even if it starts when WCV is activated but it seems it may be related to this https://wordpress.org/support/topic/4-91-the-loopback-request-to-your-site-failed/, which is a server configuration intentionally disabled by the Host.

**Comment by dvrcthewrld** [comment]
It's not related to that.  If the server configuration was incorrect, then the editor's failure to work would persist regardless of which plugins were activated.  However, the editor works fine until WCV is active.

**Comment by digitalchild** [comment]
We need more information to be able to know what the issue is. You gave us little information that just said that some plugin was reporting an issue. Only after we closed the issue did you state that there is an issue with the editor. We need repeatable steps to be able to debug and fix an issue. Please provide reproducible steps so that we can investigate this further.

**Comment by digitalchild** [comment]
This didn't make it into our release from yesterday however it'll be available in 2.1.2 or you can pull master now.
