### ISSUE TITLE
Timezone display for commissions

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#625]
**Describe the bug**

This is the first time it has been reported and we are unable to properly determine if this is related to the customer's environment or not. 

If a different timezone is set in the Settings > General then the time set in the database uses the server time not the time used in the settings. 

> I was able to duplicate the issue on the staging site. I just simply created a new order in woocommerce. The product is associated with a vendor to receive commissions. I marked the order as complete, which generated the commission. The order date is 2/5/20 and the commission date is showing 2/6/20

Commissions are stored in the database using `$order->get_date_created()` then we store it with the following -` date( 'Y-m-d H:i:s', strtotime( $order_date ).`

Need to confirm that the timezone display is actually an issue or not. If it is, we should only change the display of the date, not the stored date in the commission's table. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings > General - change the timezone to somewhere other than the server time. 
2. Process order and complete it. 
3. Check that the order time in WC Vendors > commission
4. The commission is off compared to the woocommerce order date 

**Screenshots**
![image001](https://user-images.githubusercontent.com/909468/75418835-047c9b00-5967-11ea-9c82-5bb6d18a21a0.jpg)

In this screenshot the last_updated column is added by another plugin and uses mysql date function to trigger the storage with the correct date. 

**Expected behaviour**
The order date and the commission dates should be the displaying as the same date.

**Comment by mahlamusa** [comment]
I  have found a slight difference in my dev environment that confirms the issue even though the difference is not that big, and depending on the time when the order was made.

For example, if the order date was 17-04-2020 22:00, then when calling `date(Y-m-d', strtotime('17-04-2020 22:00') );` with a timezone that is 2 hours ahead will result in the final date being 18-04-2020, which seems to be one day ahead.

Also sometimes the difference seems to be a few minutes.

Using `gmdate()` instead of `date()` results in the date being formatted as it should be regardless of the timezone of the server during runtime.

I think in some cases, it may not help to change only how the date is displayed without changing how it is saved, if the wrong date is saved then it will be incorrect when displayed.
