### ISSUE TITLE
Setting the vendor shop URL to 'authors' would cause the pagination of the vendor list to return a page not found error

### ISSUE THREAD

**Issue by junenacpil29** [wcvendors/wcvendors#638]
**Describe the bug**
If the customer were to set the vendor shop URL to authors, the pagination (clicking page 2) would return a page not found but if it was set to something else like vendors, the issue would not persist.

**To Reproduce**
1. Go to https://yourwcvendors.com/authors/ 
2. Click on the pagination (page 2) in order to see the other vendors.
3. See that it returns a page can't be found error.

**Screenshots**

**Expected behavior**
Changing the vendor shop URL to authors should work without any issues.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by junenacpil29** [comment]
the customer mentioned: "I found the cause.
The problem occurred when the Vendor Store URL and the Vendor List Page's slug name were same."

**Comment by mahlamusa** [comment]
I think it is not a good idea to have a vendor's whose name is also vendor, same like in this case, if the vendors are called Authors, why is there an author whose shop name is also Author. I understand it might be their real name but they can simply use 'author-shop' or a prefixed/suffixed slug to avoid this.

Further, I found that there are reserved words that could result in some errors in WordPress core, like causing a 404 error when the query includes such a word. `author` is one of those reserved words. More reserved are listed here: https://github.com/wcvendors/wcvendors/issues/638

I think instead of us changing the code, the store owner should prefix/suffix the `author`'s shop slug or change it to something else.

**Comment by digitalchild** [comment]
I agree that this isn't something we should be addressing. We should write a document in our docs to outline what our recommendations are. @mahlamusa can you work on that?

**Comment by mahlamusa** [comment]
Added document: https://docs.wcvendors.com/knowledge-base/reserved-words-in-wordpress/
